version: "3.7"

services:
  database:
    container_name: workplaces_database
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=workplaces_db
    ports:
      - 5432:5432
    volumes:
      - postgres_workplaces_data:/var/lib/postgresql/data 

volumes:
  postgres_workplaces_data:
    name: postgres_workplaces_data